# spring boot
spring:
  # jackson 序列化
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  # spring boot 2.0开始不支持继承配置，两个数据源要分开配置
  # 数据源
  datasource:
    druid:
      mid:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/etl_mid?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: root#root
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,logback
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 1000
      official:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/etl_official
        username: root
        password: root#root
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,logback
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 1000

## mybatis-plus
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.john.etl.*.entity
#  global-config:
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: auto
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      db-type: mariadb
#    #刷新mapper 调试神器
#    refresh: true
#  # 原生配置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

# etl
etl:
  method: multipart
  isLoadUnfinished: true
  abandonTimes: 1000
  # kafka
  kafkaProperties:
#    bootstrap-servers: 172.16.80.128:9092
    bootstrap-servers: 192.168.66.132:9092
    properties:
      spring:
        json:
          trusted:
            packages: com.john.etl.mid.mission.entity
    consumer:
      # groupId可以随便写
      group-id: testGroup
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: true
      #      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      batch-size: 16384
      # 缓存容量
      buffer-memory: 33554432
      #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      defaultTopic: etl-topic