# spring boot
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    mid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/etl_mid
      username: root
      password: root#root
    offical:
      driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/etl_official
        username: root
        password: root#root


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.john.etl.*.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mariadb
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# etl
etl:
  method:
    # multipart 多线程 single 单线程
    0
  loadUnfinished: true
  loadUnfinishedTableName:
  loadUnfinishedPosition: