version: '2'
services:
    zk_server:
        image: zookeeper
        restart: always
    kafka_server:
        image: kafka2.11:latest
        ports:
          - "9092:9092"
        environment:
          BROKER_ID: 1
        links:
          - zk_server:zkhost
        restart: always
        command: bin/kafka-server-start.sh config/server.properties
